name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
      - github

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      AWS_STACK_NAME: Dnw-OneForTwelve-Aws-Api
      AWS_S3_BUCKET: dnw-templates-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dotnet lambda tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Deploy to Lambda
        run: |
          cd ./Dnw.OneForTwelve.Aws.Api
          dotnet lambda deploy-serverless \
            --stack-name $AWS_STACK_NAME \
            --s3-bucket $AWS_S3_BUCKET \
            --region $AWS_REGION